services:
  postgres:
    image: postgres:16
    container_name: sonograma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sonograma_db
      POSTGRES_USER: sonograma_user
      POSTGRES_PASSWORD: sonograma_pass
    ports:
      - "5432:5432"
    volumes:
      - sonograma_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sonograma-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sonograma.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  sonograma_postgres_data: